data:
  raw: 
    # - "data/raw/dsm5_eng.pdf"
    - 'data/raw/dsm5.docx'

ingestion:
  cache_file: "data/cache/ingestion_cache.json"

storage:
  index_store: "data/index_store"

prompts:
  summary_extract: "prompts/summary_extract.txt"
  agent_system_template: "prompts/agent_system_template.txt"

chat:
  conversation_file: "data/cache/conversations.json"
  scores_file: "data/scores/scores.json"